DROP DATABASE IF EXISTS eflag;
CREATE DATABASE eflag;
USE eflag;
CREATE TABLE usuarios(
 id_usuario INT(6) PRIMARY KEY AUTO_INCREMENT,
 nombre VARCHAR(50) NOT NULL, 
 password VARCHAR(50) NOT NULL, 
 email VARCHAR(50) UNIQUE NOT NULL
);
CREATE TABLE peliculas(
id_pelicula INT(10) PRIMARY KEY AUTO_INCREMENT,
titulo VARCHAR(50) NOT NULL,
directores VARCHAR(200) NOT NULL,
actores VARCHAR(500) NOT NULL,
duracion INT(3) NOT NULL,
fecha_estreno CHAR(10) NOT NULL,
nota_media NUMERIC(5,3),
votos INT(3),
caratula VARCHAR(200) NOT NULL,
trailer VARCHAR(200) NOT NULL, 
generos VARCHAR(200) NOT NULL,
sinopsis VARCHAR (2000) NOT NULL
);
CREATE TABLE favoritas(
 id_pelicula INT(10),
 id_usuario INT(6),
 CONSTRAINT PK_FAVORITAS PRIMARY KEY (id_pelicula, id_usuario),
 CONSTRAINT FK_FAVORITAS_P FOREIGN KEY (id_pelicula) REFERENCES peliculas (id_pelicula) ON DELETE CASCADE,
 CONSTRAINT FK_FAVORITAS_U FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario)ON DELETE CASCADE
 );
 
 INSERT INTO usuarios VALUES(null, "arian", "arian", "a@mail");
 INSERT INTO usuarios VALUES(null, "fran", "fran", "f@mail");
 INSERT INTO peliculas VALUES(null, "arito", "bebe", "tu@mail", 120,"2017-05-19",null, null,"url", "url", "comedia", "sinopsis");
 INSERT INTO favoritas VALUES(1, 1);
 
 INSERT INTO peliculas VALUES(null, "Star Wars. Episode VII: The Force Awakens", "J.J. Abrams", "Daisy Ridley,  John Boyega,  Harrison Ford,  Adam Driver,  Oscar Isaac, Carrie Fisher,  Peter Mayhew,  Domhnall Gleeson,  Max von Sydow, Gwendoline Christie,  Lupita Nyong'o,  Andy Serkis,  Anthony Daniels,  Mark Hamill, Greg Grunberg,  Kenny Baker,  Simon Pegg,  Christina Chong,  Miltos Yerolemou, Thomas Brodie-Sangster,  Ken Leung,  Harriet Walter,  Iko Uwais,  Yayan Ruhian, Warwick Davis,  Jessica Henwick,  Daniel Craig,  Billie Lourd,  Judah Friedlander, Kevin Smith", 135,"2015-05-19",null, null,"https://pics.filmaffinity.com/star_wars_episode_vii_the_force_awakens-625343391-mmed.jpg", "https://youtu.be/FHbnQ5DUUF4", "Ciencia Ficción", "Treinta años después de la victoria de la Alianza Rebelde sobre la segunda Estrella de la Muerte (hechos narrados en el Episodio VI: El retorno del Jedi), la galaxia está todavía en guerra. Una nueva República se ha constituido, pero una siniestra organización, la Primera Orden, ha resurgido de las cenizas del Imperio Galáctico. A los héroes de antaño, que luchan ahora en la Resistencia, se suman nuevos héroes: Poe Dameron, un piloto de caza, Finn, un desertor de la Primera Orden, Rey, una joven chatarrera, y BB-8, un androide rodante. Todos ellos luchan contra las fuerzas del Mal: el Capitán Phasma, de la Primera Orden, y Kylo Ren, un temible y misterioso personaje que empuña un sable de luz roja.");	
 
 INSERT INTO peliculas VALUES(null, "The Pianist (Le Pianiste)", "Roman Polanski", "Adrien Brody,  Thomas Kretschmann,  Maureen Lipman,  Ed Stoppard,  Emilia Fox, Frank Finlay,  Julia Rayner,  Jessica Kate Meyer", 148,"2002-??-??",null, null,"http://pics.filmaffinity.com/the_pianist_le_pianiste-978132965-mmed.jpg", "https://youtu.be/itR0-I9idXk", "Drama", "Wladyslaw Szpilman, un brillante pianista polaco de origen judío, vive con su familia en el ghetto de Varsovia. Cuando, en 1939, los alemanes invaden Polonia, consigue evitar la deportación gracias a la ayuda de algunos amigos. Pero tendrá que vivir escondido y completamente aislado durante mucho tiempo, y para sobrevivir tendrá que afrontar constantes peligros.");
 
 INSERT INTO peliculas VALUES(null, "Manolito Gafotas", "Miguel Albaladejo", "David Sánchez del Rey,  Adriana Ozores,  Roberto Álvarez,  Antonio Gamero, Fedra Lorente,  Marta Fernández-Muro,  Gloria Muñoz,  Alejandro Martínez, David Martínez,  Laura Calabuig,  Sergio del Pino,  Álvaro Miranda, Belinda Washington,  Antonia San Juan", 86,"1999-05-19",null, null,"http://pics.filmaffinity.com/manolito_gafotas-555118866-mmed.jpg", "https://youtu.be/pH7NocxK324", "Comedia", "El verano se presenta francamente mal para Manolito Gafotas. Está condenado, un año más, a pasar las vacaciones en su pequeño piso de Carabanchel Alto, con su madre, su abuelo y su hermano pequeño. Y encima, para disgusto de su madre, ha suspendido las matemáticas. Manolito espera la llegada de su padre, camionero de profesión, con la ilusión de que los lleve a la playa");
 
 INSERT INTO peliculas VALUES(null, "Jack", "Francis Ford Coppola", "Robin Williams,  Diane Lane,  Jennifer Lopez,  Brian Kerwin,  Fran Drescher, Bill Cosby,  Michael McKean,  Todd Bosley", 113,"1996-05-19",null, null,"http://pics.filmaffinity.com/jack-488847615-mmed.jpg", "https://youtu.be/iHaFdSx26WM", "comedia", "Jack es un niño atrapado en un cuerpo de adulto: sufre una extraña enfermedad que hace que su crecimiento físico se cuadriplique mientras que su cerebro, que se desarrolla con normalidad, es el de un niño de diez años. No es fácil adaptarse a una vida que va a ser muy corta y esto se refleja en las relaciones con su familia y con los amigos del colegio");
 
 INSERT INTO peliculas VALUES(null, " El bueno, el feo y el malo ", "Sergio Leone", "Al Mulock, Aldo Giuffrè, Aldo Sambrell, Claudio Scarchilli, Clint Eastwood, Eli Wallach, Enzo Petito, Lee Van Cleef, Luigi Pistilli, Mario Brega, Rada Rassimov", 161,"1966-05-19",null, null,"http://image.tmdb.org/t/p/w396/ptv3EAx4Qet0G4ZdxzfKtVFwZAp.jpg", "https://youtu.be/exJOy6uTkek", "western, Drama", "Durante la guerra civil norteamericana tres cazadores de recompensas buscan un tesoro que ninguno de ellos puede encontrar sin la ayuda de los otros dos. Así que los tres colaboran entre sí para conseguir su botín, al menos en apariencia.");
 
 INSERT INTO peliculas VALUES(null, "El club de la lucha", "David Fincher", "Edward Norton,  Brad Pitt,  Helena Bonham Carter,  Meat Loaf,  Jared Leto, Van Quattro,  Markus Redmond,  Michael Girardin,  Rachel Singer,  Eion Bailey, David Lee Smith", 139,"1999-05-19",null, null,"http://pics.filmaffinity.com/fight_club-320750671-mmed.jpg", "https://youtu.be/I8892yne-ms", "Drama", "Un joven hastiado de su gris y monótona vida lucha contra el insomnio. En un viaje en avión conoce a un carismático vendedor de jabón que sostiene una teoría muy particular: el perfeccionismo es cosa de gentes débiles; sólo la autodestrucción hace que la vida merezca la pena. Ambos deciden entonces fundar un club secreto de lucha, donde poder descargar sus frustaciones y su ira, que tendrá un éxito arrollador."); 
 
 INSERT INTO peliculas VALUES(null, "La vida es bella", "Roberto Benigni", "Roberto Benigni,  Nicoletta Braschi,  Giorgio Cantarini,  Marisa Paredes, Giustino Durano,  Horst Buchholz,  Sergio Bini Bustric", 117,"1997-05-19",null, null,"http://pics.filmaffinity.com/la_vita_e_bella-646167341-mmed.jpg", "https://youtu.be/z_bgAw5KLK4", "comedia", "En 1939, a punto de estallar la Segunda Guerra Mundial (1939-1945), el extravagante Guido llega a Arezzo (Toscana) con la intención de abrir una librería. Allí conoce a Dora y, a pesar de que es la prometida del fascista Rodolfo, se casa con ella y tiene un hijo. Al estallar la guerra, los tres son internados en un campo de exterminio, donde Guido hará lo imposible para hacer creer a su hijo que la terrible situación que están padeciendo es tan sólo un juego.");
 
 INSERT INTO peliculas VALUES(null, "El padrino", "Francis Ford Coppola", "Marlon Brando,  Al Pacino,  James Caan,  Robert Duvall,  Diane Keaton,  John Cazale, Talia Shire,  Richard Castellano,  Sterling Hayden,  Gianni Russo,  Rudy Bond, John Marley,  Richard Conte,  Al Lettieri,  Abe Vigoda,  Franco Citti,  Lenny Montana, Al Martino,  Joe Spinell,  Simonetta Stefanelli,  Morgana King,  Alex Rocco, John Martino,  Salvatore Corsitto", 175,"1972-05-19",null, null,"https://pics.filmaffinity.com/the_godfather-529853536-mmed.jpg", "https://youtu.be/1aV9X2d-f5g", "Accion", "América, años 40. Don Vito Corleone (Marlon Brando) es el respetado y temido jefe de una de las cinco familias de la mafia de Nueva York. Tiene cuatro hijos: Connie (Talia Shire), el impulsivo Sonny (James Caan), el pusilánime Fredo (John Cazale) y Michael (Al Pacino), que no quiere saber nada de los negocios de su padre. Cuando Corleone, en contra de los consejos de 'Il consigliere' Tom Hagen (Robert Duvall), se niega a participar en el negocio de las drogas, el jefe de otra banda ordena su asesinato. Empieza entonces una violenta y cruenta guerra entre las familias mafiosas");
 
 
 INSERT INTO peliculas VALUES(null, "Hachiko", "Lasse Hallström", "Richard Gere,  Joan Allen,  Sarah Roemer,  Jason Alexander,  Cary-Hiroyuki Tagawa, Erick Avari,  Davenia McFadden,  Robert Capron,  Kevin DeCoste,  Bates Wilder, Robbie Sublett,  Rob Degnan,  Tora Hallstrom", 93,"2009-05-19",null, null,"https://pics.filmaffinity.com/hachi_a_dog_s_tale_hachiko_a_dog_s_story-386676685-mmed.jpg", "https://youtu.be/swp2_g0JbwY", "Drama", "Parker Wilson, un profesor universitario que da clases de música, recoge un día a un perro de origen japonés y raza Akita, al que encuentra abandonado en una estación. Como nadie lo reclama, se lo lleva a su casa. Parker va descubriendo entonces los entrañables lazos que pueden unir a una persona y a un animal. Remake de la película japonesa 'Hachiko monogatari' (1987) dirigida por Seijirô Kôyama y basada en la historia real de un perro tan fiel a su dueño que iba todos los días a esperarlo a la estación. Actualmente, en esa estación, existe una estatua de bronce erigida en su honor. ");
 
 INSERT INTO peliculas VALUES(null, "Enemigo público", "Tony Scott", "Will Smith,  Gene Hackman,  Jon Voight,  Lisa Bonet,  Jason Lee,  Ian Hart, Tom Sizemore,  Regina King,  Loren Dean,  Jake Busey,  Barry Pepper, Gabriel Byrne,  Stuart Wilson,  Jason Robards,  Philip Baker Hall,  Laura Cayouette, Seth Green,  Scott Caan,  Jack Black,  Jamie Kennedy,  Grant Heslov,  Ivana Milicevic", 132,"1998-05-19",null, null,"https://pics.filmaffinity.com/enemy_of_the_state-478413808-mmed.jpg", "https://youtu.be/R90vWtcHLlE", "Accion", "La feliz vida familiar y la brillante carrera del abogado Robert Clayton Dean están a punto de desmoronarse, cuando llega a sus manos una cinta de vídeo que contiene imágenes del asesinato de un miembro del Congreso de los Estados Unidos, en el que aparecen involucrados agentes del Gobierno.");
 
 INSERT INTO peliculas VALUES(null, "Interstellar", "Christopher Nolan", "Matthew McConaughey,  Anne Hathaway,  David Gyasi,  Jessica Chastain, Mackenzie Foy,  Matt Damon,  Michael Caine,  John Lithgow,  Casey Affleck, Timothée Chalamet,  Wes Bentley,  Ellen Burstyn,  Topher Grace,  David Oyelowo, Collette Wolfe,  Leah Cairns,  Elyes Gabel", 169,"2014-05-19",null, null,"https://pics.filmaffinity.com/interstellar-366875261-mmed.jpg", "https://youtu.be/UoSSbmD9vqc", "Ciencia ficción", "Al ver que la vida en la Tierra está llegando a su fin, un grupo de exploradores dirigidos por el piloto Cooper (McConaughey) y la científica Amelia (Hathaway) emprenden una misión que puede ser la más importante de la historia de la humanidad: viajan más allá de nuestra galaxia para descubrir otra que pueda garantizar el futuro de la raza humana.");

 INSERT INTO peliculas VALUES(null, "Shrek", "Andrew Adamson,  Vicky Jenson", "Animation", 87,"2001-05-19",null, null,"https://pics.filmaffinity.com/shrek-903764423-mmed.jpg", "https://youtu.be/jxqQPrUomTc", "comedia", "Hace mucho tiempo, en una lejanísima ciénaga, vivía un feroz ogro llamado Shrek. De repente, un día, su soledad se ve interrumpida por una invasión de sorprendentes personajes. Hay ratoncitos ciegos en su comida, un enorme y malísimo lobo en su cama, tres cerditos sin hogar y otros seres que han sido deportados de su tierra por el malvado Lord Farquaad. Para salvar su territorio, Shrek hace un pacto con Farquaad y emprende viaje para conseguir que la bella princesa Fiona acceda a ser la novia del Lord. En tan importante misión le acompaña un divertido burro, dispuesto a hacer cualquier cosa por Shrek: todo, menos guardar silencio");
 
 INSERT INTO peliculas VALUES(null, "Titanic", "James Cameron", "Leonardo DiCaprio,  Kate Winslet,  Billy Zane,  Kathy Bates,  Frances Fisher, Gloria Stuart,  Bill Paxton,  Bernard Hill,  David Warner,  Victor Garber, Jonathan Hyde,  Suzy Amis,  Danny Nucci,  Jason Barry,  Ewan Stewart, Ioan Gruffudd", 195,"1997-05-19",null, null,"https://pics.filmaffinity.com/titanic-424537916-mmed.jpg", "https://youtu.be/FiRVcExwBVA", "comedia","Jack (DiCaprio), un joven artista, gana en una partida de cartas un pasaje para viajar a América en el Titanic, el transatlántico más grande y seguro jamás construido. A bordo conoce a Rose (Kate Winslet), una joven de una buena familia venida a menos que va a contraer un matrimonio de conveniencia con Cal (Billy Zane), un millonario engreído a quien sólo interesa el prestigioso apellido de su prometida. Jack y Rose se enamoran, pero el prometido y la madre de ella ponen todo tipo de trabas a su relación. Mientras, el gigantesco y lujoso transatlántico se aproxima hacia un inmenso iceberg.");
 
 INSERT INTO peliculas VALUES(null, "Resident Evil", "Paul W.S. Anderson", "Milla Jovovich,  Michelle Rodriguez,  Eric Mabius,  James Purefoy,  Pasquale Aleardi, Stephen Billington,  Anna Bolt,  Colin Salmon,  Marisol Nichols,  Heike Makatsch, Joseph May", 96,"2002-05-19",null, null,"https://pics.filmaffinity.com/resident_evil-515947202-mmed.jpg", "https://youtu.be/cMRt9hHkljA", "Terror", "En un centro clandestino de investigación genética -con fines militares- de una poderosa multinacional se produce un brote vírico que contamina todo el edificio. Para contener la fuga el ordenador que controla el centro sella toda la instalación y, en un principio se cree que mueren todos los empleados, pero en realidad se han convertido en feroces zombis.");
 
 INSERT INTO peliculas VALUES(null, "Gladiator", "Ridley Scott", "Russell Crowe,  Joaquin Phoenix,  Connie Nielsen,  Oliver Reed,  Richard Harris, Ralf Moeller,  Derek Jacobi,  Djimon Hounsou,  David Schofield,  John Shrapnel, Spencer Treat Clark,  Tomas Arana,  David Hemmings,  Tommy Flanagan, Sven-Ole Thorsen,  Tony Curran,  Giorgio Cantarini,  Omid Djalili,  Giannina Facio, Michael Sheen", 150,"2000-05-19",null, null,"https://pics.filmaffinity.com/gladiator-152381312-mmed.jpg", "https://youtu.be/ol67qo3WhJk", "Accion", "En el año 180, el Imperio Romano domina todo el mundo conocido. Tras una gran victoria sobre los bárbaros del norte, el anciano emperador Marco Aurelio (Richard Harris) decide transferir el poder a Máximo (Russell Crowe), bravo general de sus ejércitos y hombre de inquebrantable lealtad al imperio. Pero su hijo Cómodo (Joaquin Phoenix), que aspiraba al trono, no lo acepta y trata de asesinar a Máximo");
 
 INSERT INTO peliculas VALUES(null, "Steve Jobs", "Danny Boyle", "Michael Fassbender,  Kate Winslet,  Seth Rogen,  Jeff Daniels,  Michael Stuhlbarg, Katherine Waterston,  Sarah Snook,  Perla Haney-Jardine,  Adam Shapiro, Jackie Dallas,  Makenzie Moss,  Afsheen Olyaie,  Tina Gilton,  Tom O'Reilly, Natalie Stephany Aguilar", 121,"2015-05-19",null, null,"https://pics.filmaffinity.com/steve_jobs-647763435-mmed.jpg", "https://youtu.be/CPSJaP5m_3w", "Drama" , "Biopic del mítico empresario y programador informático Steve Jobs (1955-2011), centrado en la época en la que lanzó los tres productos icónicos de Apple");
 
 INSERT INTO peliculas VALUES(null, "Charlie y la fabrica de chocolate", "Tim Burton", "Johnny Depp,  Freddie Highmore,  David Kelly,  Deep Roy,  Helena Bonham Carter, Noah Taylor,  James Fox,  Julia Winter,  Missi Pyle,  AnnaSophia Robb, Adam Godley,  Jordan Fry,  Christopher Lee,  Franziska Troegner,  Philip Wiegratz, Eileen Essell,  Liz Smith,  David Morris,  Nitin Ganatra", 116,"2005-05-19",null, null,"https://pics.filmaffinity.com/charlie_and_the_chocolate_factory-369210884-mmed.jpg", "https://youtu.be/BGem82vCZNM", "Fantastico", "Charlie Bucket (Freddie Highmore), un niño muy bueno de una familia muy pobre, gana un concurso para disfrutar de una visita de un día a la gigantesca fábrica de chocolate del excéntrico Willy Wonka (Johnny Depp) y su equipo de Oompa-Loompas. Cuatro niños más de diferentes partes del mundo lo acompañan a través de un mundo fantástico y mágico lleno de diferentes sabores");
 INSERT INTO peliculas VALUES(null, "Terminator 2", "James Cameron", "Arnold Schwarzenegger,  Linda Hamilton,  Edward Furlong,  Robert Patrick, Earl Boen,  Joe Morton,  S. Epatha Merkerson,  Michael Biehn,  Danny Cooksey, Castulo Guerra,  Jenette Goldstein,  Xander Berkeley,  Michael Edwards, Dean Norris", 135,"1991-05-19",null, null,"https://pics.filmaffinity.com/t2_terminator_2_judgment_day-825143697-mmed.jpg", "https://youtu.be/UJ4JNMdrhKI", "Accion", "Sarah Connor, la madre soltera del rebelde John Connor, está ingresada en un psiquiátrico. Algunos años antes, un viajero del tiempo le había revelado que su hijo sería el salvador de la humanidad en un futuro dominado por las máquinas. Se convirtió entonces en una especie de guerrera y educó a su hijo John en tácticas de supervivencia. Esta es la razón por la que está recluida en un manicomio. Cuando un nuevo androide mejorado, un T-1000, llega del futuro para asesinar a John, un viejo modelo T-800 será enviado para protegerle.");
  
 INSERT INTO peliculas VALUES(null, "La milla verde", "Frank Darabont", "Tom Hanks,  Michael Clarke Duncan,  David Morse,  Doug Hutchison,  Sam Rockwell, Barry Pepper,  Jeffrey DeMunn,  Michael Jeter,  Bonnie Hunt,  James Cromwell, Gary Sinise,  Patricia Clarkson,  Graham Greene,  Harry Dean Stanton, William Sadler,  Paula Malcomson,  Dabbs Greer,  Brian Libby,  Bailey Drucker", 180,"1999-05-19",null, null,"https://pics.filmaffinity.com/the_green_mile-631715339-mmed.jpg", "https://youtu.be/uDybmxbKf4Y", "Drama", "Ambientada en el sur de los Estados Unidos, en plena Depresión. Paul Edgecomb es un funcionario de prisiones encargado de vigilar la Milla Verde, un pasillo que separa las celdas de los reclusos condenados a la silla eléctrica. John Coffey, un gigantesco negro acusado de asesinar brutalmente a dos hermanas de nueve años está esperando su inminente ejecución. Tras una personalidad ingenua e infantil, Coffey esconde un prodigioso don sobrenatural. Cuando se presenta la ocasión de ponerlo en práctica, Edgecomb aprenderá que los milagros existen, incluso en los lugares más insospechados");
 INSERT INTO peliculas VALUES(null, "Pirates of Silicon Valley", "Martyn Burke", "Noah Wyle,  Anthony Michael Hall,  Joey Slotnick,  John Di Maggio,  Josh Hopkins, Melissa McBride,  Gailard Sartain,  Marcus Giamatti", 95,"1999-05-19",null, null,"https://pics.filmaffinity.com/pirates_of_silicon_valley-395977890-mmed.jpg", "https://youtu.be/hbNyIHvzC4s", "Drama", "Dos jóvenes de gran talento se enfrentan en una guerra de ingenio y estrategias comerciales para imponerse en el mercado de la informática. ");	 
  INSERT INTO favoritas VALUES(1, 1);
 
 
 
 